version: '3.5'
services:
  registry:
    container_name: eloquentlog-registry
    image: registry:2.7.1
    ports:
      - 5000:5000
    volumes:
      - ./registry-data:/var/lib/registry
    networks:
      - eloquentlog-net

  manager:
    container_name: eloquentlog-manager
    image: docker:18.09-dind
    privileged: true
    tty: true
    ports:
      - 8000:80
      - 9000:9000
    depends_on:
      - registry
    expose:
      - 3375
    command: "--insecure-registry registry:5000"
    volumes:
      - ./stack:/stack
    networks:
      - eloquentlog-net

  worker-01:
    container_name: eloquentlog-worker-01
    image: docker:18.09-dind
    privileged: true
    tty: true
    depends_on:
      - registry
      - manager
    expose:
      - 7946/tcp
      - 7946/udp
      - 4789/udp
    command: "--insecure-registry registry:5000"
    networks:
      - eloquentlog-net

  worker-02:
    container_name: eloquentlog-worker-02
    image: docker:18.09-dind
    privileged: true
    tty: true
    depends_on:
      - registry
      - manager
    expose:
      - 7946/tcp
      - 7946/udp
      - 4789/udp
    command: "--insecure-registry registry:5000"
    networks:
      - eloquentlog-net

  worker-03:
    container_name: eloquentlog-worker-03
    image: docker:18.09-dind
    privileged: true
    tty: true
    depends_on:
      - registry
      - manager
    expose:
      - 7946/tcp
      - 7946/udp
      - 4789/udp
    command: "--insecure-registry registry:5000"
    networks:
      - eloquentlog-net

networks:
  eloquentlog-net:
    name: eloquentlog-net
    driver: bridge
    external: true
  default:
    external:
      name: eloquentlog-net
