version: '3.2'
services:
  master:
    hostname: master
    image: sameersbn/postgresql:10-1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role != manager
    environment:
      DEBUG: 'false'
      DB_USER: eloquentlog
      DB_PASS: eloquentlog
      DB_NAME: eloquentlog_development
      REPLICATION_MODE: master
      REPLICATION_SSLMODE:
      REPLICATION_USER: eloquentlog_replicator
      REPLICATION_PASS: eloquentlog_replicator
    depends_on:
      - data
    volumes:
      - type: volume
        source: eloquentlog-data
        target: /var/lib/postgresql/
        volume:
          nocopy: false
    networks:
      - eloquentlog

  slave:
    hostname: slave
    image: sameersbn/postgresql:10-1
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role != manager
    environment:
      DEBUG: 'false'
      REPLICATION_MODE: slave
      REPLICATION_HOST: master
      REPLICATION_USER: eloquentlog_replicator
      REPLICATION_PASS: eloquentlog_replicator
    depends_on:
      - master
    networks:
      - eloquentlog

  # copy files into the data vomule
  data:
    image: registry:5000/eloquentlog/eloquentlog-data:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role != manager
    volumes:
      - type: volume
        source: eloquentlog-data
        target: /var/lib/postgresql/
        volume:
          nocopy: false
    networks:
      - eloquentlog

volumes:
  eloquentlog-data:

networks:
  eloquentlog:
    external: true
