version: '3'
services:
  app:
    image: dockersamples/visualizer
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - '9000:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
